[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
dex = { address = "EZDyb8s4DgMksN6aPx7gbeZ8B7SjWms3YuXu3VgUT11T", path = "programs/dex" }

[programs.mainnet]
dex = { address = "EZDyb8s4DgMksN6aPx7gbeZ8B7SjWms3YuXu3VgUT11T", path = "programs/dex" }

[registry]
url = "https://api.apr.dev"

[workspace]
members = ["programs/*"]

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
