[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dex = "11111111111111111111111111111111"

[programs.mainnet]
dex = "EZDyb8s4DgMksN6aPx7gbeZ8B7SjWms3YuXu3VgUT11T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
